spring.application.name=task_collap

spring.datasource.url=jdbc:postgresql://localhost:1234/task_db
spring.datasource.username=ADMIN
spring.datasource.password=${DB_PASSWORD:admin123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:q<hosVl6bLFW,T2B<-^S02p9/P@D=kET$c/(-.]QYB3}

server.port=1717

spring.output.ansi.enabled=ALWAYS
spring.web.error.include-message=ALWAYS
